### ISSUE TITLE
运行main.py程序报错

### ISSUE THREAD

**Issue by developerwithpassion** [YuxingLu613/Prompt-NER-Chinese#1]
作者你好，我在Windows环境下运行程序，出现如下错误：
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    loss = CrossEntropyloss(outputs, label_ids)
  File "D:\code\python\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\code\python\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\loss.py", line 1047, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "D:\code\python\Anaconda\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 2693, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\code\python\Anaconda\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 2388, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss_forward

**Comment by YuxingLu613** [comment]
我的理解是你的output和label的类型不一致，一个是long，一个是float，可以尝试把label的类型转换为long试试

**Comment by developerwithpassion** [comment]
感谢回复。数据集使用的是项目中自带的，代码也没改动。
在linux环境是能运行的。不过2080ti速度好慢。

**Comment by Hzzhang-nlp** [comment]
> 我的理解是你的output和label的类型不一致，一个是long，一个是float，可以尝试把label的类型转换为long试试

兄弟，你项目里面的提示词呢？
